<x-app-layout>
    <x-slot name="header">Blocked report</x-slot>
    <div class="space-y-6">
        <section class="card"><p class="text-sm font-bold uppercase tracking-[0.25em] text-indigo-600">Blocked time report</p><h2 class="mt-3 text-3xl font-black tracking-tight text-slate-950">Blockers and elapsed time</h2><p class="mt-2 text-slate-600">{{ $isClientUser ? 'Summarized blocker reasons for your organization without internal timer detail.' : 'Detailed internal blockage analysis including owner, reason, resolution, and elapsed time.' }}</p></section>
        @include('reports.partials.filters', ['action' => route('reports.blocked'), 'exportRoute' => route('reports.export.blocked')])
        @include('reports.partials.cards', ['cards' => ['blocked_hours' => number_format($totalSeconds / 3600, 2), 'block_events' => $blocks->total()]])
        <section class="card overflow-hidden p-0"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200 text-sm"><thead class="bg-slate-50 text-left text-xs font-black uppercase tracking-wide text-slate-500"><tr><th class="px-5 py-4">Ticket</th><th class="px-5 py-4">Client / Software</th>@if (! $isClientUser)<th class="px-5 py-4">Blocked by</th>@endif<th class="px-5 py-4">Timing</th><th class="px-5 py-4">Reason</th><th class="px-5 py-4">Hours</th></tr></thead><tbody class="divide-y divide-slate-100 bg-white">@forelse ($blocks as $block)<tr><td class="px-5 py-4"><a class="font-black text-indigo-700" href="{{ route('tickets.show', $block->ticket) }}">{{ $block->ticket?->ticket_no }}</a><p class="text-xs font-semibold text-slate-500">{{ $block->ticket?->title }}</p></td><td class="px-5 py-4 font-semibold text-slate-600">{{ $block->ticket?->client?->name }}<br><span class="text-xs">{{ $block->ticket?->software?->name }}</span></td>@if (! $isClientUser)<td class="px-5 py-4">{{ $block->blocker?->name ?? '—' }}</td>@endif<td class="px-5 py-4 text-xs font-semibold text-slate-500">{{ $block->blocked_at?->format('M j, Y g:i A') }}<br>{{ $block->unblocked_at?->format('M j, Y g:i A') ?? 'Still blocked' }}</td><td class="px-5 py-4 font-semibold text-slate-600">{{ $block->reason }}@if (! $isClientUser && $block->unblock_note)<br><span class="text-xs text-slate-500">Resolved: {{ $block->unblock_note }}</span>@endif</td><td class="px-5 py-4 font-black text-slate-900">{{ number_format($block->currentDurationSeconds() / 3600, 2) }}</td></tr>@empty<tr><td colspan="6" class="px-5 py-12 text-center font-semibold text-slate-500">No blocked time matches the current filters.</td></tr>@endforelse</tbody></table></div><div class="border-t border-slate-100 px-5 py-4">{{ $blocks->links() }}</div></section>
    </div>
</x-app-layout>
