<x-app-layout>
    <x-slot name="header">Sprint report</x-slot>
    <div class="space-y-6">
        <section class="card"><p class="text-sm font-bold uppercase tracking-[0.25em] text-indigo-600">Sprint summary report</p><h2 class="mt-3 text-3xl font-black tracking-tight text-slate-950">Sprint outcomes</h2><p class="mt-2 text-slate-600">Summarize active and completed sprint cycles by organization, software, status, and date.</p></section>
        @include('reports.partials.filters', ['action' => route('reports.sprints'), 'exportRoute' => route('reports.export.sprints')])
        @include('reports.partials.cards', ['cards' => $summary])
        <section class="card overflow-hidden p-0"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200 text-sm"><thead class="bg-slate-50 text-left text-xs font-black uppercase tracking-wide text-slate-500"><tr><th class="px-5 py-4">Sprint</th><th class="px-5 py-4">Client / Software</th><th class="px-5 py-4">Status</th><th class="px-5 py-4">Timing</th><th class="px-5 py-4">Tickets</th></tr></thead><tbody class="divide-y divide-slate-100 bg-white">@forelse ($sprints as $sprint)<tr><td class="px-5 py-4"><a class="font-black text-indigo-700" href="{{ route('sprints.show', $sprint) }}">{{ $sprint->name }}</a><p class="text-xs font-semibold text-slate-500">Cycle #{{ $sprint->sprint_no }}</p></td><td class="px-5 py-4 font-semibold text-slate-600">{{ $sprint->client?->name }}<br><span class="text-xs">{{ $sprint->software?->name ?? 'Multiple software' }}</span></td><td class="px-5 py-4">{{ $sprint->formattedStatus() }}</td><td class="px-5 py-4 text-xs font-semibold text-slate-500">{{ $sprint->started_at?->format('M j, Y g:i A') ?? 'Not started' }}<br>{{ $sprint->ended_at?->format('M j, Y g:i A') ?? 'Open' }}<br>{{ $sprint->formattedDuration() }}</td><td class="px-5 py-4 font-black text-slate-900">{{ $sprint->items_count }}</td></tr>@empty<tr><td colspan="5" class="px-5 py-12 text-center font-semibold text-slate-500">No sprints match the current filters.</td></tr>@endforelse</tbody></table></div><div class="border-t border-slate-100 px-5 py-4">{{ $sprints->links() }}</div></section>
    </div>
</x-app-layout>
