<x-app-layout>
    <x-slot name="header">Tickets report</x-slot>
    <div class="space-y-6">
        <section class="card"><p class="text-sm font-bold uppercase tracking-[0.25em] text-indigo-600">Tickets report</p><h2 class="mt-3 text-3xl font-black tracking-tight text-slate-950">Ticket pipeline</h2><p class="mt-2 text-slate-600">Review ticket mix, current statuses, assignment, blockers, and due dates.</p></section>
        @include('reports.partials.filters', ['action' => route('reports.tickets'), 'exportRoute' => route('reports.export.tickets')])
        @include('reports.partials.cards', ['cards' => $summary])
        <section class="card overflow-hidden p-0"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200 text-sm"><thead class="bg-slate-50 text-left text-xs font-black uppercase tracking-wide text-slate-500"><tr><th class="px-5 py-4">Ticket</th><th class="px-5 py-4">Type / Status</th><th class="px-5 py-4">Client / Software</th><th class="px-5 py-4">People</th><th class="px-5 py-4">Due</th></tr></thead><tbody class="divide-y divide-slate-100 bg-white">@forelse ($tickets as $ticket)<tr><td class="px-5 py-4"><a class="font-black text-indigo-700" href="{{ route('tickets.show', $ticket) }}">{{ $ticket->ticket_no }}</a><p class="text-xs font-semibold text-slate-500">{{ $ticket->title }}</p></td><td class="px-5 py-4 font-semibold text-slate-600">{{ $ticket->formattedUrgency() }} {{ str($ticket->type)->headline() }}<br><span class="text-xs">{{ $ticket->formattedStatus() }}</span></td><td class="px-5 py-4 font-semibold text-slate-600">{{ $ticket->client?->name }}<br><span class="text-xs">{{ $ticket->software?->name ?? 'No software' }}</span></td><td class="px-5 py-4 text-xs font-semibold text-slate-500">Submitted: {{ $ticket->submitter?->name ?? '—' }}<br>Assigned: {{ $ticket->assignee?->name ?? '—' }}</td><td class="px-5 py-4 font-semibold text-slate-600">{{ $ticket->due_date?->format('M j, Y') ?? '—' }}</td></tr>@empty<tr><td colspan="5" class="px-5 py-12 text-center font-semibold text-slate-500">No tickets match the current filters.</td></tr>@endforelse</tbody></table></div><div class="border-t border-slate-100 px-5 py-4">{{ $tickets->links() }}</div></section>
    </div>
</x-app-layout>
