<x-app-layout>
    <x-slot name="header">Time report</x-slot>
    <div class="space-y-6">
        <section class="card"><p class="text-sm font-bold uppercase tracking-[0.25em] text-indigo-600">Time tracking report</p><h2 class="mt-3 text-3xl font-black tracking-tight text-slate-950">Tracked delivery time</h2><p class="mt-2 text-slate-600">{{ $isClientUser ? 'Summarized organization-level effort. Internal timer details are hidden from client exports.' : 'Detailed internal timer records for delivery analysis and CSV export.' }}</p></section>
        @include('reports.partials.filters', ['action' => route('reports.time'), 'exportRoute' => route('reports.export.time')])
        @include('reports.partials.cards', ['cards' => ['total_hours' => number_format($totalSeconds / 3600, 2), 'entries' => $logs->total()]])
        <section class="card overflow-hidden p-0"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200 text-sm"><thead class="bg-slate-50 text-left text-xs font-black uppercase tracking-wide text-slate-500"><tr><th class="px-5 py-4">Ticket</th><th class="px-5 py-4">Client / Software</th>@if (! $isClientUser)<th class="px-5 py-4">User</th>@endif<th class="px-5 py-4">Window</th><th class="px-5 py-4">Hours</th><th class="px-5 py-4">Status</th></tr></thead><tbody class="divide-y divide-slate-100 bg-white">@forelse ($logs as $log)<tr><td class="px-5 py-4"><a class="font-black text-indigo-700" href="{{ route('tickets.show', $log->ticket) }}">{{ $log->ticket?->ticket_no }}</a><p class="text-xs font-semibold text-slate-500">{{ $log->ticket?->title }}</p></td><td class="px-5 py-4 font-semibold text-slate-600">{{ $log->client?->name ?? $log->ticket?->client?->name }}<br><span class="text-xs">{{ $log->software?->name ?? $log->ticket?->software?->name }}</span></td>@if (! $isClientUser)<td class="px-5 py-4">{{ $log->user?->name }}</td>@endif<td class="px-5 py-4 text-xs font-semibold text-slate-500">{{ $log->started_at?->format('M j, Y g:i A') }}<br>{{ $log->ended_at?->format('M j, Y g:i A') ?? 'Running / paused' }}</td><td class="px-5 py-4 font-black text-slate-900">{{ number_format($log->duration_seconds / 3600, 2) }}</td><td class="px-5 py-4">{{ str($log->status)->headline() }}</td></tr>@empty<tr><td colspan="6" class="px-5 py-12 text-center font-semibold text-slate-500">No time entries match the current filters.</td></tr>@endforelse</tbody></table></div><div class="border-t border-slate-100 px-5 py-4">{{ $logs->links() }}</div></section>
    </div>
</x-app-layout>
