<div x-cloak x-show="createFeatureDrawerOpen" class="fixed inset-0 z-[120]" @keydown.escape.window="closeCreateFeatureDrawer()">
    <div x-show="createFeatureDrawerOpen" x-transition.opacity class="absolute inset-0 bg-slate-950/40" @click="closeCreateFeatureDrawer()"></div>
    <aside x-show="createFeatureDrawerOpen" x-transition:enter="duration-200 ease-out" x-transition:enter-start="translate-x-full" x-transition:enter-end="translate-x-0" x-transition:leave="duration-150 ease-in" x-transition:leave-start="translate-x-0" x-transition:leave-end="translate-x-full" class="absolute right-0 top-0 h-full w-full max-w-xl bg-white shadow-2xl" @click.stop>
        <div class="flex h-full flex-col">
            <div class="flex items-center justify-between border-b border-slate-200 px-6 py-4"><h3 class="text-lg font-black text-slate-950">Feature Request</h3><button type="button" class="rounded-lg p-2 text-slate-500 hover:bg-slate-100" @click="closeCreateFeatureDrawer()"><svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor"><path fill-rule="evenodd" d="M4.22 4.22a.75.75 0 0 1 1.06 0L10 8.94l4.72-4.72a.75.75 0 1 1 1.06 1.06L11.06 10l4.72 4.72a.75.75 0 1 1-1.06 1.06L10 11.06l-4.72 4.72a.75.75 0 1 1-1.06-1.06L8.94 10 4.22 5.28a.75.75 0 0 1 0-1.06Z" clip-rule="evenodd"/></svg></button></div>
            <form class="flex-1 overflow-y-auto space-y-4 px-6 py-5" @submit.prevent="submitCreateFeature">
                <template x-if="createFeatureErrors.global"><p class="rounded-lg border border-rose-200 bg-rose-50 px-3 py-2 text-sm text-rose-700" x-text="createFeatureErrors.global"></p></template>
                <label class="block text-sm font-semibold">Title<input x-model="createFeatureForm.title" x-ref="createFeatureTitle" class="mt-1 w-full rounded-xl border-slate-200" required></label><p x-show="createFeatureErrors.title" x-text="createFeatureErrors.title" class="text-xs text-rose-600"></p>
                <label class="block text-sm font-semibold">Description<textarea x-model="createFeatureForm.description" rows="4" class="mt-1 w-full rounded-xl border-slate-200" required></textarea></label><p x-show="createFeatureErrors.description" x-text="createFeatureErrors.description" class="text-xs text-rose-600"></p>
                <label class="block text-sm font-semibold">Software<select x-model="createFeatureForm.software_id" class="mt-1 w-full rounded-xl border-slate-200" required><option value="">Select software</option>@foreach($softwares as $software)<option value="{{ $software->id }}">{{ $software->name }}</option>@endforeach</select></label><p x-show="createFeatureErrors.software_id" x-text="createFeatureErrors.software_id" class="text-xs text-rose-600"></p>
                <label class="block text-sm font-semibold">Urgency<select x-model="createFeatureForm.urgency" class="mt-1 w-full rounded-xl border-slate-200" required><option value="">Select urgency</option>@foreach(
App\Models\Ticket::URGENCIES as $urgency)<option value="{{ $urgency }}">{{ str($urgency)->headline() }}</option>@endforeach</select></label><p x-show="createFeatureErrors.urgency" x-text="createFeatureErrors.urgency" class="text-xs text-rose-600"></p>
                <div class="flex justify-end gap-2 pt-2"><button type="button" class="rounded-xl border px-4 py-2" @click="closeCreateFeatureDrawer()">Cancel</button><button type="submit" class="rounded-xl bg-indigo-600 px-4 py-2 text-white" :disabled="createFeatureSubmitting"><span x-show="!createFeatureSubmitting">Create Feature</span><span x-show="createFeatureSubmitting">Creating…</span></button></div>
            </form>
        </div>
    </aside>
</div>
